version: '3.7'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  node:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ./frontend/:/code
      - /code/node_modules
      - /code/.next
    links: 
      - db

volumes:
  postgres-data:

networks:
  default:
    name: new_django_project
    