# Generated by Django 2.2.16 on 2020-10-14 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 14, 12, 53, 8, 125555)),
        ),
    ]
